import { getUrlSmartTrader, getUrlBinaryBot } from '../url/helpers';
import { deriv_urls } from '../url/constants';

export const routes = {
    error404: '/404',
    account: `${deriv_urls.DERIV_APP_PRODUCTION}/account`,
    financial_assessment: `${deriv_urls.DERIV_APP_PRODUCTION}/account/financial-assessment`,
    personal_details: `${deriv_urls.DERIV_APP_PRODUCTION}/account/personal-details`,
    proof_of_identity: `${deriv_urls.DERIV_APP_PRODUCTION}/account/proof-of-identity`,
    proof_of_address: `${deriv_urls.DERIV_APP_PRODUCTION}/account/proof-of-address`,
    passwords: `${deriv_urls.DERIV_APP_PRODUCTION}/account/passwords`,
    closing_account: `${deriv_urls.DERIV_APP_PRODUCTION}/account/closing-account`,
    deactivate_account: `${deriv_urls.DERIV_APP_PRODUCTION}/account/deactivate-account`, // TODO: Remove once mobile team has changed this link
    account_closed: `${deriv_urls.DERIV_APP_PRODUCTION}/account-closed`,
    account_limits: `${deriv_urls.DERIV_APP_PRODUCTION}/account/account-limits`,
    connected_apps: `${deriv_urls.DERIV_APP_PRODUCTION}/account/connected-apps`,
    api_token: `${deriv_urls.DERIV_APP_PRODUCTION}/account/api-token`,
    login_history: `${deriv_urls.DERIV_APP_PRODUCTION}/account/login-history`,
    two_factor_authentication: `${deriv_urls.DERIV_APP_PRODUCTION}/account/two-factor-authentication`,
    self_exclusion: `${deriv_urls.DERIV_APP_PRODUCTION}/account/self-exclusion`,
    account_password: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/account_password`,
    apps: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/apps`,
    cashier_password: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/cashier_password`,
    contract: `${deriv_urls.DERIV_APP_PRODUCTION}/contract/:contract_id`,
    exclusion: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/exclusion`,
    financial: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/financial`,
    history: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/history`,
    index: `${deriv_urls.DERIV_APP_PRODUCTION}/index`,
    limits: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/limits`,
    mt5: `${deriv_urls.DERIV_APP_PRODUCTION}/mt5`,
    dxtrade: `${deriv_urls.DERIV_APP_PRODUCTION}/derivx`,
    personal: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/personal`,
    positions: `${deriv_urls.DERIV_APP_PRODUCTION}/reports/positions`,
    profit: `${deriv_urls.DERIV_APP_PRODUCTION}/reports/profit`,
    reports: `${deriv_urls.DERIV_APP_PRODUCTION}/reports`,
    root: '/',
    reset_password: '/',
    redirect: '/redirect',
    settings: `${deriv_urls.DERIV_APP_PRODUCTION}/settings`,
    statement: `${deriv_urls.DERIV_APP_PRODUCTION}/reports/statement`,
    token: `${deriv_urls.DERIV_APP_PRODUCTION}/settings/token`,
    trade: `${deriv_urls.DERIV_APP_PRODUCTION}`,
    bot: `${deriv_urls.DERIV_APP_PRODUCTION}/bot`,
    deriv_air: '/',
    cashier: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier`,
    cashier_deposit: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/deposit`,
    cashier_withdrawal: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/withdrawal`,
    cashier_pa: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/payment-agent`,
    cashier_acc_transfer: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/account-transfer`,
    cashier_crypto_transactions: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/crypto-transactions`,
    // cashier_offramp: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/off-ramp`,
    cashier_onramp: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/on-ramp`,
    cashier_p2p: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/p2p`,
    cashier_p2p_verification: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/p2p/verification`,
    cashier_pa_transfer: `${deriv_urls.DERIV_APP_PRODUCTION}/cashier/payment-agent-transfer`,
    smarttrader: getUrlSmartTrader(),
    binarybot: getUrlBinaryBot(),
    endpoint: '/endpoint',
    complaints_policy: `${deriv_urls.DERIV_APP_PRODUCTION}/complaints-policy`,

    // Appstore
    trading_hub: `${deriv_urls.DERIV_APP_PRODUCTION}/trading-hub`,
};
